CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    marca VARCHAR(255),
    categoria VARCHAR(255),
    sku VARCHAR(255),
    fornecedor_principal_id BIGINT,
    preco_venda NUMERIC(12, 2) NOT NULL,
    preco_custo NUMERIC(12, 2) NOT NULL,
    volume_ml NUMERIC(10, 2),
    estoque_atual INT NOT NULL,
    estoque_minimo INT NOT NULL,
    user_id INT NOT NULL DEFAULT 1,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT NOT NULL DEFAULT 1,
    atualizado_por BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT produtos_pk PRIMARY KEY (id),
    CONSTRAINT uk_produtos_sku_user_id UNIQUE (sku, user_id)
);

CREATE INDEX idx_produtos_user_id ON produtos (user_id);
