CREATE TABLE custos_insumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    custo_unitario NUMERIC(12, 2) NOT NULL,
    unidade VARCHAR(50),
    user_id INT NOT NULL DEFAULT 1,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT NOT NULL DEFAULT 1,
    atualizado_por BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT custos_insumo_pk PRIMARY KEY (id)
);

CREATE INDEX idx_custos_insumo_user_id ON custos_insumo (user_id);
