CREATE TABLE decantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    produto_id BIGINT NOT NULL,
    volume_ml NUMERIC(10, 2) NOT NULL,
    preco_venda NUMERIC(12, 2) NOT NULL,
    custo_embalagem NUMERIC(12, 2) NOT NULL,
    custo_seringa NUMERIC(12, 2) NOT NULL,
    custo_etiqueta NUMERIC(12, 2) NOT NULL,
    user_id INT NOT NULL DEFAULT 1,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT NOT NULL DEFAULT 1,
    atualizado_por BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT decantes_pk PRIMARY KEY (id),
    CONSTRAINT fk_decantes_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE INDEX idx_decantes_produto_id ON decantes (produto_id);
CREATE INDEX idx_decantes_user_id ON decantes (user_id);
