CREATE TABLE marcas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    pais VARCHAR(255),
    user_id INT NOT NULL DEFAULT 1,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT NOT NULL DEFAULT 1,
    atualizado_por BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT marcas_pk PRIMARY KEY (id),
    CONSTRAINT uk_marcas_nome_user_id UNIQUE (nome, user_id)
);

CREATE INDEX idx_marcas_user_id ON marcas (user_id);

-- Liga produtos a marcas. Coluna nova primeiro, backfill do texto existente, depois a FK.
ALTER TABLE produtos ADD COLUMN marca_id BIGINT;

INSERT INTO marcas (nome, user_id)
SELECT DISTINCT TRIM(marca), user_id
FROM produtos
WHERE marca IS NOT NULL AND TRIM(marca) <> '';

UPDATE produtos p
SET marca_id = m.id
FROM marcas m
WHERE m.nome = TRIM(p.marca) AND m.user_id = p.user_id;

ALTER TABLE produtos DROP COLUMN marca;

ALTER TABLE produtos ADD CONSTRAINT fk_produtos_marca FOREIGN KEY (marca_id) REFERENCES marcas (id);
CREATE INDEX idx_produtos_marca_id ON produtos (marca_id);
