CREATE TABLE lotes_compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    produto_id BIGINT NOT NULL,
    data_compra DATE NOT NULL DEFAULT CURRENT_DATE,
    quantidade_frascos INT NOT NULL,
    preco_unitario NUMERIC(12, 2) NOT NULL,
    custo_adicional NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fornecedor VARCHAR(255),
    observacao VARCHAR(500),
    user_id INT NOT NULL DEFAULT 1,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT NOT NULL DEFAULT 1,
    atualizado_por BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT lotes_compra_pk PRIMARY KEY (id),
    CONSTRAINT fk_lotes_compra_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE INDEX idx_lotes_compra_produto_id ON lotes_compra (produto_id);
CREATE INDEX idx_lotes_compra_user_id ON lotes_compra (user_id);
CREATE INDEX idx_lotes_compra_data_compra ON lotes_compra (data_compra);
