CREATE TABLE frascos_abertos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    produto_id BIGINT NOT NULL,
    data_abertura DATE NOT NULL DEFAULT CURRENT_DATE,
    volume_inicial_ml NUMERIC(10, 2) NOT NULL,
    ml_restante NUMERIC(10, 2) NOT NULL,
    status VARCHAR(15) NOT NULL DEFAULT 'ABERTO',
    observacao VARCHAR(500),
    user_id INT NOT NULL DEFAULT 1,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT NOT NULL DEFAULT 1,
    atualizado_por BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT frascos_abertos_pk PRIMARY KEY (id),
    CONSTRAINT fk_frascos_abertos_produto FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE INDEX idx_frascos_abertos_produto_id ON frascos_abertos (produto_id);
CREATE INDEX idx_frascos_abertos_status ON frascos_abertos (status);
CREATE INDEX idx_frascos_abertos_user_id ON frascos_abertos (user_id);
