CREATE TABLE vendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    produto_id BIGINT NOT NULL,
    data_venda DATE NOT NULL DEFAULT CURRENT_DATE,
    tipo VARCHAR(20) NOT NULL,
    decante_id BIGINT,
    frasco_aberto_id BIGINT,
    quantidade INT NOT NULL,
    volume_unitario_ml NUMERIC(10, 2) NOT NULL,
    preco_unitario NUMERIC(12, 2) NOT NULL,
    custo_unitario NUMERIC(12, 2) NOT NULL,
    receita_total NUMERIC(12, 2) NOT NULL,
    lucro_total NUMERIC(12, 2) NOT NULL,
    forma_pagamento VARCHAR(30),
    observacao VARCHAR(500),
    user_id INT NOT NULL DEFAULT 1,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    criado_por BIGINT NOT NULL DEFAULT 1,
    atualizado_por BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT vendas_pk PRIMARY KEY (id),
    CONSTRAINT fk_vendas_produto FOREIGN KEY (produto_id) REFERENCES produtos (id),
    CONSTRAINT fk_vendas_decante FOREIGN KEY (decante_id) REFERENCES decantes (id),
    CONSTRAINT fk_vendas_frasco_aberto FOREIGN KEY (frasco_aberto_id) REFERENCES frascos_abertos (id)
);

CREATE INDEX idx_vendas_produto_id ON vendas (produto_id);
CREATE INDEX idx_vendas_user_id ON vendas (user_id);
CREATE INDEX idx_vendas_data_venda ON vendas (data_venda);
CREATE INDEX idx_vendas_tipo ON vendas (tipo);
